### ISSUE TITLE
create_profile not defined

### ISSUE THREAD

**Issue by arjun27** [vsls-contrib/spaces#79]
when I run the server, I'm seeing

```
warning: function LiveShareCommunities.ProfileStore.create_profile/1 is undefined or private. Did you mean one of:

      * create_profile/3

  lib/communities/http.ex:202
```

it seems we have a different method signature for create_profile in the profile store. cc @legomushroom

**Comment by legomushroom** [comment]
PR: https://github.com/vsls-contrib/communities/pull/80
