### ISSUE TITLE
Load profile pic from the connected live share account

### ISSUE THREAD

**Issue by RandomFractals** [vsls-contrib/spaces#83]
in my case it was my github account. Happy to see you pulled profile name as defined there instead of just github handle.

would be nice to have the profile pic loaded automatically in chat too:

![vsls-data-community](https://user-images.githubusercontent.com/656833/64266209-dce9d000-cef9-11e9-9e6a-088b67ff32ea.png)

**Comment by RandomFractals** [comment]
so, I just found 29 settings for vsls, still no way to set my profile pic. 

@arjun27 what am I missing beyond you'll add it from github in your next rev.

somehow you & @lostintangent have your custom icons in that chat :(

![vsls-profile-pic-setting](https://user-images.githubusercontent.com/656833/64648037-c05d0480-d3df-11e9-8ad0-d09631206899.png)

**Comment by arjun27** [comment]
The icons in the chat are being pulled from Gravatar right now - and we created the issue to add support to GitHub avatars.

Live Share profiles reuse avatars associated with GitHub or Azure Active Directory accounts. To get the consistency in the chat, we would get to AAD support (pref after GitHub is supported).

Feel free to submit PRs to chat in case you'd like to see this getting prioritized sooner :)

The relevant code is at https://github.com/vsls-contrib/chat/blob/3c88482ceedd928f5e203c905cbff7a9d521cd30/src/vslsCommunities/index.ts#L126

**Comment by RandomFractals** [comment]
nah! this is good for now. thanks!

**Comment by RandomFractals** [comment]
not to nit pick but would be nice if you could capture dev's pic, motto & profile link on 'member hover' like I do it in this js notebook User Info section: ...

https://observablehq.com/@randomfractals/notebook-info

|| how overservable does it on top. I like that ;)

**Comment by RandomFractals** [comment]
@arjun27 not sure this is your final, but I think you can expend on that hover...

![vsls-member-hover](https://user-images.githubusercontent.com/656833/64652761-3d8d7700-d3ea-11e9-8832-2f179b3770b8.png)

**Comment by RandomFractals** [comment]
feel free to split & log that last issue in this repo || chat. 

I'm gonna give you guys some rest for a bit to work out those remote data loads ;)

cheers!

p.s.: I hope you liked my feedback on your beta in a week. let's reconcile mid September?

**Comment by lostintangent** [comment]
Closing this since it’s a Chat request.
