### ISSUE TITLE
question: Is live share status based on vscode window being active or auto setting?

### ISSUE THREAD

**Issue by RandomFractals** [vsls-contrib/spaces#85]
I believe I let Live Share run on auto. Then I changed my status to Available.

As I am connected and move to other windows after some time (a few minutes or so) I see my live share and communities member status being changed to Away automatically.

Tried resetting it a few times to Available again. It goes back to Away again after some time. Most likely some general Live Share nooby feature I am not aware of, but it's irritating.

**Comment by arjun27** [comment]
Thanks @RandomFractals. I'm not sure if I follow this. Does the presence status not change to available when you return back to the window?

**Comment by RandomFractals** [comment]
no, it doesn't. Also, I am not sure I want it that way, especially if I set it to Available. Even if I step up for 5 mins, I don't think it should change to Away automatically. will see if there is a setting I can toggle for that.

**Comment by RandomFractals** [comment]
did not find a setting for it. 

would it be possible to add 1 with 'set to Away' after x minutes of inactivity, or something along those lines?

**Comment by lostintangent** [comment]
This is really a request on Live Share, since the Spaces extension just builds on top of its presence support.
