### ISSUE TITLE
@communities & the rest of that beta test sess.:

### ISSUE THREAD

**Issue by RandomFractals** [vsls-contrib/spaces#86]
![vsls-communities-feedback](https://user-images.githubusercontent.com/656833/64275987-6d311080-cf0c-11e9-9b6f-e6a7db05c581.png)

**Comment by arjun27** [comment]
Thanks, interesting idea. I wonder if `#community` might be better since Slack has established `@user` and `#channel`

**Comment by RandomFractals** [comment]
yeah, I like #<community> || #<user> too. that way it would be easy to tag folks and other communities to check out convos/answers etc.

**Comment by lostintangent** [comment]
This has now been implemented
