### ISSUE TITLE
Fan art

### ISSUE THREAD

**Issue by legomushroom** [vsls-contrib/spaces#90]
I deeply appreciate what you are doing guys, some fan art to cheer you up!

..................<img src="https://user-images.githubusercontent.com/1478800/64374319-3250da80-cfe9-11e9-9ea0-8cb4518954a9.png" width="502" />

This is how it might look like on the extension avatar(click to expand):
![tg-vscode](https://user-images.githubusercontent.com/1478800/64374501-9ffd0680-cfe9-11e9-914d-85d504cd73e6.png)

**Comment by RandomFractals** [comment]
@legomushroom I 💖 it! You got all kinds of coders represented in that icon.

Reminds me of that African proverb: want to go fast, go alone, want to go far, go together. or something like that.

@arjun27 & @lostintangent I think you guys should use this icon for your community ext. when you go GA.

**Comment by lostintangent** [comment]
This has been merged in 🤗
