### ISSUE TITLE
sending all msgs on vsls community room reconnect? why?

### ISSUE THREAD

**Issue by RandomFractals** [vsls-contrib/spaces#93]
![vsls-sending-all-msgs](https://user-images.githubusercontent.com/656833/64636321-12ddf700-d3c7-11e9-96fc-be2520bb0aab.png)

**Comment by RandomFractals** [comment]
I think some of them could be cached if you don't allow msg edits.. also, most likely I don't need all 52 msgs that don't fit in that screen. just the last few ;)

**Comment by RandomFractals** [comment]
@lostintangent & @arjun27  any update on this bit? I do this it's a bit too eager & excessive ...

**Comment by arjun27** [comment]
Thanks for sharing. This issue belongs to the chat extension, and I'll move it there. The chat webview uses Vue, which internally optimizes the DOM updates to avoid redundant rendering, which makes this issue less of a priority, as a compared to some basic chat features (like editing messages). Let me know if there's any reason to prioritize this.
